'use strict';

/**
 * @callback getPreferenceFn
 * @returns {void}
 */

/**
 * Custom preference abstraction object
 * @typedef {Object} CustomPreference
 * @property {getPreferenceFn} getValue - Gets the value.
 */

// @doc https://documentation.b2c.commercecloud.salesforce.com/DOC2/index.jsp?topic=%2Fcom.demandware.dochelp%2FActiveMerchandising%2FDynamicGroupAttributeTypes.html
var Types = {
    string: 'string',
    int: 'int',
    boolean: 'boolean',
    date: 'date',
    SetOfString: 'set-of-string',
    EnumOfString: 'enum-of-string',
    SetOfInt: 'set-of-int',
    EnumOfInt: 'enum-of-int',
    Password: 'password'
};

module.exports = {
    Core: {
        id: 'Cybersource_Core',
        display_name: 'Cybersource Cartridge configuration',
        Preferences: {
            /** @type {CustomPreference} */
            CartridgeEnabled: {
                id: 'Cybersource_CartridgeEnabled',
                display_name: 'Enable Cybersource Cartridge',
                description: 'Enable or disable Cybersource Cartridge. If disabled none of the Cybersource services are invoked.',
                type: Types.boolean,
                default: true,
                flags: {
                    mandatory: true
                }
            },
            /** @type {CustomPreference} */
            MerchantID: {
                id: 'Cybersource_MerchantID',
                display_name: 'Cybersource MerchantID',
                description: 'Cybersource Merchant ID',
                type: Types.string,
                default: undefined,
                flags: {
                    mandatory: true
                }
            },
            /** @type {CustomPreference} */
            MerchantKeyId: {
                id: 'Cybersource_MerchantKeyId',
                display_name: 'Cybersource REST KeyId',
                description: 'Cybersource REST Key ID',
                type: Types.string,
                default: undefined,
                flags: {
                    mandatory: true
                }
            },
            /** @type {CustomPreference} */
            MerchantKeySecret: {
                id: 'Cybersource_MerchantKeySecret',
                display_name: 'Cybersource REST Secret Key',
                description: 'Cybersource REST Secret Key',
                type: Types.Password,
                default: undefined,
                flags: {
                    mandatory: true
                }
            },
            /** @type {CustomPreference} */
            DeveloperId: {
                id: 'Cybersource_DeveloperId',
                display_name: 'DeveloperId',
                description: 'Unique identifier generated by Cybersource for System Integrator',
                type: Types.string,
                default: undefined,
                flags: {
                    mandatory: false
                }
            },
            /** @type {CustomPreference} */
            CommerceIndicator: {
                id: 'Cybersource_CommerceIndicator' ,
                display_name: 'Commerce Indicator',
                description: '',
                type: Types.EnumOfString,
                default: 'internet',
                flags: {
                    mandatory: false
                }
            }
        }
    },

    DeliveryAddressVerification: {
        id: 'Cybersource_DeliveryAddressVerification',
        display_name: 'Delivery Address Verification Configuration',
        Preferences: {
            /** @type {CustomPreference} */
            DAVEnabled: {
                id: 'Cybersource_DAVEnabled',
                display_name: 'Enable Delivery Address Verification Services',
                description: 'Enable or Disable Delivery Address Verification for Cybersource Cartridge',
                type: Types.boolean,
                default: true,
                flags: {
                    mandatory: false
                }
            }
        }
    },

    TaxConfiguration: {
        id: 'Cybersource_TaxConfiguration',
        display_name: 'Tax Calulation Configuration',
        Preferences: {
            /** @type {CustomPreference} */
            TaxCalculationEnabled: {
                id: 'Cybersource_TaxCalculationEnabled',
                display_name: 'Enable Tax calculation Services',
                description: 'Enables or Disables Tax calculation for Cybersource Cartridge',
                type: Types.boolean,
                default: true,
                flags: {
                    mandatory: false
                }
            },

            /** @type {CustomPreference} */
            NexusStateList: {
                id: 'Cybersource_NexusStateList',
                display_name: 'List of nexus states',
                description: "When your company has nexus in the U.S. or Canada, you might be required to collect sales tax or seller's use tax in those countries",
                type: Types.SetOfString,
                default: false,
                flags: {
                    mandatory: false
                }
            },

            /** @type {CustomPreference} */
            NoNexusStateList: {
                id: 'Cybersource_NoNexusStateList',
                display_name: 'List of nexus states to exclude',
                description: 'List of nexus states to exclude',
                type: Types.SetOfString,
                default: false,
                flags: {
                    mandatory: false
                }
            },

            /** @type {CustomPreference} */
            VatRegistrationNumber: {
                id: 'Cybersource_VatRegistrationNumber',
                display_name: "Merchant's VAT Registration Number",
                description: 'A VAT seller registration number is required in order to calculate international taxes and might be required for some Canadian transactions. International/VAT calculation is supported in specific countries',
                type: Types.string,
                default: '',
                flags: {
                    mandatory: false
                }
            },

            /** @type {CustomPreference} */
            DefaultProductTaxCode: {
                id: 'Cybersource_DefaultProductTaxCode',
                display_name: 'Default Product Tax Code',
                description: 'Default tax code used when tax code is not set on a product',
                type: Types.string,
                default: '5310',
                flags: {
                    mandatory: false
                }
            },

            /** @type {CustomPreference} */
            PurchaseOrderAcceptanceCity: {
                id: 'Cybersource_PurchaseOrderAcceptanceCity',
                display_name: 'Purchase Order Acceptance City',
                description: 'Purchase Order Acceptance City',
                type: Types.string,
                default: 'Lyndhurst',
                flags: {
                    mandatory: false
                }
            },

            /** @type {CustomPreference} */
            PurchaseOrderAcceptanceStateCode: {
                id: 'Cybersource_PurchaseOrderAcceptanceStateCode',
                display_name: 'Purchase Order Acceptance State Code',
                description: 'Purchase Order Acceptance State Code. Use the State, Province, and Territory Codes for the United States and Canada',
                type: Types.string,
                default: 'NJ',
                flags: {
                    mandatory: false
                }
            },

            /** @type {CustomPreference} */
            PurchaseOrderAcceptanceZipCode: {
                id: 'Cybersource_PurchaseOrderAcceptanceZipCode',
                display_name: 'Purchase Order Acceptance zip code',
                description: 'Purchase Order Acceptance zip code',
                type: Types.string,
                default: '07071',
                flags: {
                    mandatory: false
                }
            },

            /** @type {CustomPreference} */
            PurchaseOrderAcceptanceCountryCode: {
                id: 'Cybersource_PurchaseOrderAcceptanceCountryCode',
                display_name: 'Purchase Order Acceptance Country Code',
                description: 'Purchase Order Acceptance Country Code.  Use the two-character ISO Standard Country Codes',
                type: Types.string,
                default: 'US',
                flags: {
                    mandatory: false
                }
            },

            /** @type {CustomPreference} */
            PurchaseOrderOriginCity: {
                id: 'Cybersource_PurchaseOrderOriginCity',
                display_name: 'Purchase Order Origin City',
                description: 'Purchase Order Origin City',
                type: Types.string,
                default: 'Lyndhurst',
                flags: {
                    mandatory: false
                }
            },

            /** @type {CustomPreference} */
            PurchaseOrderOriginStateCode: {
                id: 'Cybersource_PurchaseOrderOriginStateCode',
                display_name: 'Purchase Order Origin State Code',
                description: 'Purchase Order Origin State Code. Use the State, Province, and Territory Codes for the United States and Canada',
                type: Types.string,
                default: 'NJ',
                flags: {
                    mandatory: false
                }
            },

            /** @type {CustomPreference} */
            PurchaseOrderOriginZipCode: {
                id: 'Cybersource_PurchaseOrderOriginZipCode',
                display_name: 'Purchase Order Origin Zip Code',
                description: 'Purchase Order Origin Zip Code',
                type: Types.string,
                default: '07071',
                flags: {
                    mandatory: false
                }
            },

            /** @type {CustomPreference} */
            PurchaseOrderOriginCountryCode: {
                id: 'Cybersource_PurchaseOrderOriginCountryCode',
                display_name: 'Purchase Order Origin Country Code',
                description: 'Purchase Order Origin Country Code. Use the two-character ISO Standard Country Codes',
                type: Types.string,
                default: 'US',
                flags: {
                    mandatory: false
                }
            },

            /** @type {CustomPreference} */
            ShipFromCity: {
                id: 'Cybersource_ShipFromCity',
                display_name: 'Ship From City',
                description: 'Ship From City',
                type: Types.string,
                default: 'Lyndhurst',
                flags: {
                    mandatory: false
                }
            },

            /** @type {CustomPreference} */
            ShipFromStateCode: {
                id: 'Cybersource_ShipFromStateCode',
                display_name: 'Ship From State Code',
                description: 'Ship From State Code',
                type: Types.string,
                default: 'NJ',
                flags: {
                    mandatory: false
                }
            },

            /** @type {CustomPreference} */
            ShipFromZipCode: {
                id: 'Cybersource_ShipFromZipCode',
                display_name: 'Ship From Zip Code',
                description: 'Ship From Zip Code',
                type: Types.string,
                default: '07071',
                flags: {
                    mandatory: false
                }
            },

            /** @type {CustomPreference} */
            ShipFromCountryCode: {
                id: 'Cybersource_ShipFromCountryCode',
                display_name: 'Ship From Country Code',
                description: 'Ship From Country Code',
                type: Types.string,
                default: 'US',
                flags: {
                    mandatory: false
                }
            }
        }
    },

    Tokenization: {
        id: 'Cybersource_Tokenization',
        display_name: 'Tokenization Configuration',
        Preferences: {
            /** @type {CustomPreference} */
            TokenizationEnabled: {
                id: 'Cybersource_TokenizationEnabled',
                display_name: 'Enable Tokenization Services',
                description: 'Enable or Disable the Tokenization Service saving Credit Card on My Account page',
                type: Types.boolean,
                default: true,
                flags: {
                    mandatory: false
                }
            },
            /** @type {CustomPreference} */
            LimitSavedCardEnabled: {
                id: 'Cybersource_LimitSavedCardEnabled',
                display_name: 'Enable limiting Saved Card',
                description: 'Enable or Disable limiting Saved Card on My Account page',
                type: Types.boolean,
                default: true,
                flags: {
                    mandatory: false
                }
            },
            /** @type {CustomPreference} */
            PaymentInstrumentAllowedInInterval: {
                id: 'Cybersource_PaymentInstrumentAllowedInInterval',
                display_name: 'Saved Card Allowed',
                description: 'Number of Cards that can be added in a defined interval on My Account page',
                type: Types.int,
                default: 20,
                flags: {
                    mandatory: false
                }
            },
             /** @type {CustomPreference} */
             NetworkTokenUpdates: {
                id: 'Cybersource_NetworkToken',
                display_name: 'Network Token Updates',
                description: 'Subscribe to Network Token life cycle updates',
                type: Types.boolean,
                default: false,
                flags: {
                    mandatory: false
                }
            },
            /** @type {CustomPreference} */
            ResetIntervalInHours: {
                id: 'Cybersource_ResetIntervalInHours',
                display_name: 'Reset Interval (in Hours)',
                description: 'Number of hours that saved card attempts are counted',
                type: Types.int,
                default: 1,
                flags: {
                    mandatory: false
                }
            }
        }
    },

    FlexMicroform: {
        id: 'Cybersource_FlexMicroform',
        display_name: 'Flex Microform Configuration',
        Preferences: {
            /** @type {CustomPreference} */
            FlexMicroformEnabled: {
                id: 'Cybersource_FlexMicroform',
                display_name: 'Enable Secure Acceptance - Flex Microfrom',
                description: 'Enable or Disable Cybersource Flex Microform service',
                type: Types.boolean,
                default: true,
                flags: {
                    mandatory: false
                }
            }
        }
    },

    DecisionManager: {
        id: 'Cybersource_DecisionManager',
        display_name: 'Decision Manager Configuration',
        Preferences: {
            /** @type {CustomPreference} */
            DecisionManagerEnabled: {
                id: 'Cybersource_DecisionManager',
                display_name: 'Enable Decision Manager Services',
                description: 'Enable or Disable Decision Manager for Cybersource Cartridge',
                type: Types.boolean,
                default: true,
                flags: {
                    mandatory: false
                }
            },
            /** @type {CustomPreference} */
            ConversionDetailReportLookbackTime: {
                id: 'Cybersource_ConversionDetailReportLookbackTime',
                display_name: 'Conversion Detail Report Lookback time',
                description: 'Number of hours the job will look back for new decisions. CS does not support lookbacks over 24 hours. Do not set above 24',
                type: Types.int,
                default: '23',
                flags: {
                    mandatory: false
                }
            }
        }
    },

    DeviceFingerprint: {
        id: 'Cybersource_DeviceFingerprint',
        display_name: 'Device Finger Print Configuration',
        Preferences: {
            /** @type {CustomPreference} */
            DeviceFingerprintEnabled: {
                id: 'Cybersource_DeviceFingerprintEnabled',
                display_name: 'Enable DeviceFingerprint Service',
                description: 'Enable or Disable DeviceFingerprint for Cybersource Cartridge',
                type: Types.boolean,
                default: true,
                flags: {
                    mandatory: false
                }
            },
            /** @type {CustomPreference} */
            OrganizationId: {
                id: 'Cybersource_OrganizationId',
                display_name: 'Organization id',
                description: 'TOrganization ID for the device fingerprint check',
                type: Types.string,
                default: '1snn5n9w',
                flags: {
                    mandatory: false
                }
            },
            /** @type {CustomPreference} */
            ThreadMatrixUrl: {
                id: 'Cybersource_ThreadMatrixUrl',
                display_name: 'Thread Matrix Url',
                description: 'Thread Matrix URL pointing to JS that generates and retrieves the fingerprint',
                type: Types.string,
                default: 'https://h.online-metrix.net',
                flags: {
                    mandatory: false
                }
            },
            /** @type {CustomPreference} */
            TimeToLive: {
                id: 'Cybersource_DeviceFingerprintTTL',
                display_name: 'TTL (Time To Live)',
                description: 'Time, in milliseconds between generating a new fingerprint for any given customer session',
                type: Types.string,
                default: '86,400,000',
                flags: {
                    mandatory: false
                }
            }
        }
    },

    /** Payer Authentication Custom Preference */
    PayerAuthentication: {
        id: 'Cybersource_PayerAuthentication',
        display_name: 'Payer Authentication Configuration',
        Preferences: {
            /** @type {CustomPreference} */
            EnablePayerAuthentication: {
                id: 'Cybersource_PayerAuthEnabled',
                display_name: 'Enable Payer Authentication',
                description: 'Enable or Disable Payer Authentication service',
                type: Types.boolean,
                default: false,
                flags: {
                    mandatory: false
                }
            },
        }
    },
    /* Google Pay Custom Preference */
    GooglePay: {
        id: 'Cybersource_GooglePay',
        display_name: '',
        Preferences: {
            /** @type {CustomPreference} */
            EnableGooglePay: {
                id: 'Cybersource_EnableGooglePay',
                display_name: 'Enable Google Pay',
                description: '',
                type: Types.boolean,
                default: false,
                flags: {
                    mandatory: false
                }
            },
            /** @type {CustomPreference} */
            GooglePayEnvironment: {
                id: 'Cybersource_GooglePayEnvironment',
                display_name: 'Google Pay Environment',
                description: '',
                type: Types.EnumOfString,
                default: 'TEST',
                flags: {
                    mandatory: false
                }
            },
            /** @type {CustomPreference} */
            EnableGooglePayOnMiniCart: {
                id: 'Cybersource_EnableGooglePayOnMiniCart',
                display_name: 'Enable Google Pay On Mini Cart',
                description: '',
                type: Types.boolean,
                default: false,
                flags: {
                    mandatory: false
                }
            },
            /** @type {CustomPreference} */
            EnableGooglePayOnCart: {
                id: 'Cybersource_EnableGooglePayOnCart',
                display_name: 'Enable Google Pay On Cart',
                description: '',
                type: Types.boolean,
                default: false,
                flags: {
                    mandatory: false
                }
            },
            /** @type {CustomPreference} */
            GooglePayMerchantId: {
                id: 'Cybersource_GooglePayMerchantId',
                display_name: 'Google Pay MerchantId',
                description: '',
                type: Types.string,
                default: undefined,
                flags: {
                    mandatory: false
                }
            }
        }
    },

    ClicktoPay: {
        id: 'Cybersource_ClicktoPay',
        display_name: '',
        Preferences: {
            ClicktoPayProduction: {
                id: 'Cybersource_ClicktoPayProduction',
                display_name: 'True for production',
                description: '',
                type: Types.boolean,
                default: false,
                flags: {
                    mandatory: false
                }
            },
            ClicktoPayEnabled: {
                id: 'Cybersource_ClicktoPayEnabled',
                display_name: 'Enable Click to Pay',
                description: '',
                type: Types.boolean,
                default: false,
                flags: {
                    mandatory: false
                }
            },
            ClicktoPayKey: {
                id: 'Cybersource_ClicktoPayKey',
                display_name: 'Click to Pay Key',
                description: '',
                type: Types.string,
                default: false,
                flags: {
                    mandatory: false
                }
            }
        }
    },

 /* MLE Custom Preference */
 MLE: {
    id: 'Cybersource_MLE',
    display_name: 'Message-Level Encryption Configration',
    Preferences: {
        /** @type {CustomPreference} */
        EnableMLE: {
            id: 'Cybersource_MLEEnabled',
            display_name: 'Enable Message-Level Encryption',
            description: 'Enable or Disable Message-Level Encryption.',
            type: Types.boolean,
            default: false,
            flags: {
                mandatory: false
            }
        },
        /** @type {CustomPreference} */
        MLECertificateSerialNumber: {
            id: 'Cybersource_CertificateSerialNo',
            display_name: 'Certificate Serial Number',
            description: 'Serial Number of "CyberSource_SJC_US" certificate extracted from p12 file.',
            type: Types.string,
            default: undefined,
            flags: {
                mandatory: false
            }
        },
         /** @type {CustomPreference} */
         MLECertificateAlias: {
            id: 'Cybersource_CertificateAlias',
            display_name: 'Alias of the Certificate',
            description: '',
            type: Types.string,
            default: undefined,
            flags: {
                mandatory: false
            }
        }
    }
},   
};
